import { act, renderHook } from "@testing-library/react-native";
import { AppState } from "react-native";
import { useTripTracking } from "@/hooks/useTripTracking";
import { useRiderLocation } from "@/hooks/useRiderLocation";
import { useActiveTrip } from "@/store/activeTrip";
import { useSession } from "@/store/session";
import * as api from "@/lib/api";
jest.mock("@/hooks/useRiderLocation",()=>({useRiderLocation:jest.fn()}));
jest.mock("@/lib/api",()=>({...jest.requireActual("@/lib/api"),postLocation:jest.fn(async()=>({}))}));
it("publishes for the trip independently of route, pauses in background and stops on revocation",async()=>{
  jest.useFakeTimers();
  let change:(state:"active"|"background")=>void=()=>{};
  const listener=jest.spyOn(AppState,"addEventListener").mockImplementation((_event,fn)=>{change=fn;return {remove:jest.fn()};});
  const user={id:"r",role:"rider" as const,name:"R",email:"r@test",verificationStatus:"approved" as const};
  useSession.setState({user});
  useActiveTrip.setState({order:{id:"o",riderId:"r",state:"out_for_delivery"} as api.Order});
  const fix={coords:{lat:7,lng:125},accuracy:8,fixAtMs:Date.now(),permission:"granted",heading:null,speed:null,error:null};
  (useRiderLocation as jest.Mock).mockImplementation(({enabled})=>enabled?fix:{...fix,coords:null,fixAtMs:null});
  await renderHook(()=>useTripTracking());
  expect(api.postLocation).toHaveBeenCalledWith("o",expect.objectContaining({recordedAt:new Date(fix.fixAtMs).toISOString()}));
  await act(async()=>{change("background");});
  const before=(api.postLocation as jest.Mock).mock.calls.length;
  await act(async()=>{jest.advanceTimersByTime(30_000);});
  expect(api.postLocation).toHaveBeenCalledTimes(before);
  await act(async()=>{change("active");});
  expect((api.postLocation as jest.Mock).mock.calls.length).toBeGreaterThan(before);
  await act(async()=>{useSession.setState({user:{...user,verificationStatus:"suspended"}});});
  expect(useActiveTrip.getState().order).toBeNull();
  const last=(api.postLocation as jest.Mock).mock.calls.length;
  await act(async()=>{jest.advanceTimersByTime(30_000);});
  expect(api.postLocation).toHaveBeenCalledTimes(last);
  listener.mockRestore();jest.useRealTimers();
});
